### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mtartila** [Hantoo/Unity_MQTT#1]
i was trying to learn from your file until i tested the mqtt test knowing i couldnt run the script

**Comment by Hantoo** [comment]
Please could you elaborate on what you mean buy compile error?
If you have the error : 
_SocketException: No connection could be made because the target machine actively refused it._
**OR**
_SocketException: A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a send to call) no address was supplied._
then please make sure that you have your MQTT broker running on the client machine. When testing I used [Mosquitto](https://mosquitto.org/)

**Comment by mtartila** [comment]
thanks, ive actually successfully connected the mqtt, but do you possibly know how to convert the subscribed message as an input for unity  ( to float/int variable as an input)

**Comment by Hantoo** [comment]
Within the MQTTRouting Script and by using "MqttMessage.Message".
Since you should know how the message value will be parsed you can cast this to whatever you need it to be - I.e taken from the routing script:
String Example:
`string Messagestring = System.Text.Encoding.UTF8.GetString(MqttMessage.Message);`
OR Bool Example:
`bool Messagebool = bool.Parse(System.Text.Encoding.UTF8.GetString(MqttMessage.Message));`
OR Int Example:
`TotalPeopleOverall = int.Parse(System.Text.Encoding.UTF8.GetString(MqttMessage.Message));`

**Comment by mtartila** [comment]
okay thank you but last question, do i need to use it on mqttrouting or can i use it on any script? i tried using the example youve give on mqttTest.cs
int.Parse(System.Text.Encoding.UTF8.GetString(MqttMessage.Message));
and it says 
"the name 'temperature' does not exist in the current context.

**Comment by Hantoo** [comment]
The MQTT Messages received are not global and are passed directly into the MQTTRouting script. Use the MQTT Routing script to break down the MQTT topic and grab the message. Then I would suggest passing the value from the message into a method that sets your temperature variable in another script.
I.e.
```
if (MqttMessage.Topic.Contains("Global/Temperature"))
{
    TemperatureControl TempCtrl = new TemperatureControl ();
    int value = int.Parse(System.Text.Encoding.UTF8.GetString(MqttMessage.Message));
    TempCtrl .setTemp(value );
}
```
